name: DeployPythonApp

on:
  push:
    branches:
      - master
      - actions/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build app using Oryx v2-beta and CDN
      uses: kichalla/oryxaction@master
      with:
        source-directory: sampleApps/python/django-app
        platform: python
        platform-version: 3.7

    - name: Print variables
      run: printenv

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: kichallaFlaskApp37
        publish-profile: ${{ secrets.kichallapythonapp }}
        package: ${{ env.RUNNER_TEMP }}/oryx-output
